# vi docker-compose.yml
version: '3.3'
services:
    mongo:
        ports:
            - '27017:27017'
        container_name: docker-mongo
        restart: always
        logging:
            options:
                max-size: 1g
        environment:
            - MONGO_INITDB_ROOT_USERNAME=mongoadmin
            - MONGO_INITDB_ROOT_PASSWORD=passwd
        image: mongo

    app:
        container_name: docker-app
        build: ./
        volumes:
            - ./:/app
            - ./init.sh:/docker-entrypoint-initdb.d/init.sh
        restart: unless-stopped
        env_file: .env
        environment:
            - MONGO_URI=${MONGO_URI}
            - secret=${secret}
            - name=${name}
            - email=${email}
            - password=${password}
        ports:
            - '3000:3000'
        entrypoint: sh -c "npm start && npm run test"
        network_mode: 'host'
                
        
